name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  apictl:
    runs-on: ubuntu-latest
    env: 
      APICTL_CONFIG_DIR: /__w/apictl-workflow/apictl-workflow/master-ci
    container:
      image: malinthaprasan/apictl
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Checkout CI config
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master-ci
          path: master-ci
      - run: |
          apictl login cloud40 -u admin -p admin
          apictl import api -f PetStore-1.0.6 -e cloud40 --update --rotate-revision
